base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('account/', include('account.urls', namespace='account')),
    path('otp/', include('otp.urls', namespace='otp')),
    path('user/', include('customer.urls', namespace='customer')),
    path('staff/', include('staff.urls', namespace='staff')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

otp/urls.py
from django.urls import path
from . import views

app_name = 'otp'

urlpatterns = [
    path('login-verify/', views.login_verify_otp_view, name='login_verify_otp'),
    path('resend-otp/', views.resend_otp_view, name='resend_otp'),
]

staff/urls.py
from django.urls import path

from . import views

app_name = 'staff'

urlpatterns = [
    path('dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('customer/<int:user_id>/detail/',views.admin_customer_detail_view,
    name='admin_customer_detail'),
    path("customer/<int:user_id>/edit/", views.admin_edit_customer_view,
    name="admin_edit_customer"),
    path("customers/<int:user_id>/delete/", views.admin_delete_customer_view,
    name="admin_delete_customer"),

    path('plans/', views.admin_plan_list_view,name='admin_plan_list'),
    path('plan/create/', views.admin_plan_create_view,name='admin_plan_create'),
    path('plan/<int:pk>/edit/', views.admin_plan_edit_view,
    name='admin_plan_edit'),
    path('plan/<int:pk>/delete/', views.admin_plan_delete_view,
    name='admin_plan_delete'),

    path('pending-deposits/', views.admin_deposit_requests_view, name='admin_deposit_requests'),
    path('pending-withdrawals/', views.admin_withdraw_requests_view, name='admin_withdraw_requests'),

    path('kyc-list/', views.admin_kyc_list_view,name='admin_kyc_list'),
    path('kyc/<int:kyc_id>/review/', views.admin_kyc_review_view,
    name='admin_kyc_review'),

    path('snapshot-positive/<int:order_id>/', views.snapshot_positive_view,
    name='snapshot_positive'),
    path('snapshot-negative/<int:order_id>/', views.snapshot_negative_view,
    name='snapshot_negative'),

    path('vip-requests/', views.vip_requests_admin,
    name='vip_requests'),
    path('vip_request_action/<int:request_id>/<str:action>/', views.vip_request_action,
    name='vip_request_action'),
]

account/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django_countries.fields import CountryField

from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=255)
    nick_name = models.CharField(max_length=255)

    # Address fields
    address = models.TextField(null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    country = models.CharField(max_length=250, null=True, blank=True)
    zipcode = models.CharField(max_length=20, null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_email_verified = models.BooleanField(default=False)
    is_vip = models.BooleanField(default=False)
    can_be_copied = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']

    objects = UserManager()

    def __str__(self):
        return self.email
    

class VIPRequest(models.Model):
    PENDING = 'pending'
    APPROVED = 'approved'
    REJECTED = 'rejected'

    STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (APPROVED, 'Approved'),
        (REJECTED, 'Rejected'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='vip_requests')
    requested_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=PENDING)
    admin_note = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['-requested_at']

    def __str__(self):
        return f"{self.user.email} - {self.status}"
    

class KYC(models.Model):
    # --------------------
    # Status choices
    # --------------------
    STATUS_NOT_SUBMITTED = 'NOT_SUBMITTED'
    STATUS_PENDING = 'PENDING'
    STATUS_VERIFIED = 'VERIFIED'
    STATUS_REJECTED = 'REJECTED'

    STATUS_CHOICES = [
        (STATUS_NOT_SUBMITTED, 'Not Submitted'),
        (STATUS_PENDING, 'Pending Review'),
        (STATUS_VERIFIED, 'Verified'),
        (STATUS_REJECTED, 'Rejected'),
    ]

    # --------------------
    # Relations
    # --------------------
    portfolio = models.OneToOneField(
        'customer.Portfolio',
        on_delete=models.CASCADE,
        related_name='kyc'
    )

    # --------------------
    # Personal Information
    # --------------------
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    nationality = models.CharField(max_length=100, null=True, blank=True)

    # --------------------
    # Identity Document
    # --------------------
    DOCUMENT_PASSPORT = 'PASSPORT'
    DOCUMENT_NATIONAL_ID = 'NATIONAL_ID'
    DOCUMENT_DRIVER_LICENSE = 'DRIVERS_LICENSE'

    DOCUMENT_TYPE_CHOICES = [
        (DOCUMENT_PASSPORT, 'Passport'),
        (DOCUMENT_NATIONAL_ID, 'National ID'),
        (DOCUMENT_DRIVER_LICENSE, "Driver’s License"),
    ]

    document_type = models.CharField(
        max_length=30,
        choices=DOCUMENT_TYPE_CHOICES,
        null=True,
        blank=True
    )
    document_number = models.CharField(max_length=100, null=True, blank=True)
    document_image = models.ImageField(
        upload_to='kyc/documents/',
        null=True,
        blank=True
    )

    # --------------------
    # Proof of Address
    # --------------------
    address = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    address_proof = models.ImageField(
        upload_to='kyc/address/',
        null=True,
        blank=True
    )

    # --------------------
    # KYC Status
    # --------------------
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default=STATUS_NOT_SUBMITTED
    )

    submitted_at = models.DateTimeField(null=True, blank=True)
    reviewed_at = models.DateTimeField(null=True, blank=True)
    rejection_reason = models.TextField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # --------------------
    # Helpers
    # --------------------
    def __str__(self):
        return f"KYC ({self.get_status_display()}) - {self.portfolio.user.email}"

    @property
    def is_verified(self):
        return self.status == self.STATUS_VERIFIED

plan/models.py
# app/models.py
from decimal import Decimal, ROUND_HALF_EVEN
from django.conf import settings
from django.db import models, transaction
from django.utils import timezone

class Plan(models.Model):

    class PlanType(models.TextChoices):
        CRYPTO = "CRYPTO", "Crypto"
        REIT = "REIT", "Reit"
        STOCK = "STOCK", "Stock"

    name = models.CharField(max_length=200)

    plantype = models.CharField(
        max_length=10,
        choices=PlanType.choices,
        default=PlanType.CRYPTO
    )

    percent_increment = models.DecimalField(
        max_digits=6,
        decimal_places=4,
        help_text="Daily percent (e.g., 0.5000 for 0.5%)"
    )

    duration_days = models.PositiveIntegerField(null=True, blank=True)

    min_amount = models.DecimalField(
        max_digits=20,
        decimal_places=2,
        default=Decimal('0.00')
    )

    is_featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.name} - {self.get_plantype_display()} ({self.percent_increment}%)"

class OrderPlan(models.Model):
    STATUS_ACTIVE = 'active'
    STATUS_PAUSED = 'paused'
    STATUS_CANCELLED = 'cancelled'
    STATUS_COMPLETED = 'completed'
    STATUS_CHOICES = [
        (STATUS_ACTIVE, 'Active'),
        (STATUS_PAUSED, 'Paused'),
        (STATUS_CANCELLED, 'Cancelled'),
        (STATUS_COMPLETED, 'Completed'),
    ]

    portfolio = models.ForeignKey('customer.Portfolio', on_delete=models.CASCADE)
    plan = models.ForeignKey(Plan, on_delete=models.PROTECT)
    principal_amount = models.DecimalField(max_digits=20, decimal_places=2)
    current_value = models.DecimalField(max_digits=20, decimal_places=2)
    start_at = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_ACTIVE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [
            models.Index(fields=['status', 'start_at']),
        ]

    def __str__(self):
        return f"OrderPlan #{self.pk} - {self.portfolio.user} - {self.plan.name}"

    def recompute_current_value(self):
        """Recompute current_value as principal + sum of all delta_amounts from items."""
        total_delta = self.items.aggregate(total=models.Sum('delta_amount'))['total'] or Decimal('0.00')
        new_value = (self.principal_amount + total_delta).quantize(Decimal('0.01'), rounding=ROUND_HALF_EVEN)
        self.current_value = new_value
        self.save(update_fields=['current_value'])
        return self.current_value


class OrderPlanItem(models.Model):
    order_plan = models.ForeignKey(OrderPlan, on_delete=models.CASCADE, related_name='items')
    snapshot_at = models.DateTimeField()
    delta_amount = models.DecimalField(max_digits=20, decimal_places=2)
    percent_applied = models.DecimalField(max_digits=6, decimal_places=4)
    cumulative_amount = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    note = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        # unique_together = ('order_plan', 'snapshot_at')
        indexes = [
            models.Index(fields=['order_plan', 'snapshot_at']),
        ]

    def __str__(self):
        return f"Snapshot {self.snapshot_at} for OrderPlan {self.order_plan_id}"


class TransactionLog(models.Model):
    order_plan = models.ForeignKey(OrderPlan, on_delete=models.CASCADE, related_name='transactions')
    before_value = models.DecimalField(max_digits=20, decimal_places=2)
    change_amount = models.DecimalField(max_digits=20, decimal_places=2)
    after_value = models.DecimalField(max_digits=20, decimal_places=2)
    reason = models.CharField(max_length=255)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=['order_plan', 'created_at']),
        ]

    def __str__(self):
        return f"Txn for OrderPlan {self.order_plan_id} at {self.created_at}"

staff/models.py
from django.db import models

# Create your models here.

plan/forms.py
from django import forms
from .models import Plan


class PlanForm(forms.ModelForm):

    class Meta:
        model = Plan
        fields = [
            "name",
            "plantype",
            "percent_increment",
            # "duration_days",
            "min_amount",
            "is_featured",
        ]

        widgets = {
            "name": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter plan name"
            }),

            "plantype": forms.Select(attrs={
                "class": "form-select"
            }),

            "percent_increment": forms.NumberInput(attrs={
                "class": "form-control",
                "step": "0.0001",
                "placeholder": "0.5000"
            }),

            # "duration_days": forms.NumberInput(attrs={
            #     "class": "form-control",
            #     "placeholder": "Optional duration in days"
            # }),

            "min_amount": forms.NumberInput(attrs={
                "class": "form-control",
                "step": "0.01"
            }),

            "is_featured": forms.CheckboxInput(attrs={
                "class": "form-check-input"
            }),
        }

templates/staff/customer_detail.html
{% extends "../customer/base.html" %}
{% load humanize %}

{% block title %}Customer Detail{% endblock %}

{% block content %}

<!-- Customer Profile Section -->
<div class="card shadow-sm mb-5">
    <div class="card-body">
        <div class="row align-items-center">

            <!-- Customer Image -->
            <div class="col-md-3 text-center mb-3 mb-md-0">
                <img src="https://via.placeholder.com/150x150" class="img-fluid rounded-circle border" alt="Customer Image"
                    style="width:150px; height:150px; object-fit:cover;">
            </div>

            <!-- Customer Details -->
            <div class="col-md-9">
                <h3 class="mb-3">{{customer.full_name}}</h3>

                <div class="row">
                    <div class="col-md-6">
                        <p><strong>Email:</strong> {{customer.email}}</p>
                        <p><strong>Country:</strong> {{customer.country}}</p>
                        <p><strong>Status:</strong>
                            {% if customer.is_vip %}
                                <span class="badge bg-success">VIP</span>
                            {% else %}
                                <span class="badge bg-warning">Not VIP</span>
                            {% endif %}
                        </p>
                    </div>

                    <div class="col-md-6">
                        <p><strong>KYC:</strong>
                            {% if customer.portfolio.is_kyc_verified %}
                                <span class="badge bg-success">Verified</span>
                            {% else %}
                                <span class="badge bg-warning">Not Verified</span>
                            {% endif %}
                        </p>
                        <p><strong>Joined:</strong> {{customer.date_joined}}</p>
                        <p><strong>Total Active Plans:</strong> {{order_plan_count}}</p>
                    </div>
                </div>

                <!-- Admin Actions -->
                <div class="mt-3">
                    <!-- <button class="btn btn-outline-primary btn-sm">
                        <i class="bi bi-pencil"></i> Edit Profile
                    </button> -->
                    <!-- <button class="btn btn-outline-danger btn-sm">
                        <i class="bi bi-ban"></i> Suspend
                    </button> -->
                </div>
            </div>

        </div>
    </div>
</div>
{% include "../notification/messages.html" %}
<!-- Active Plans Section -->
<div class="d-flex justify-content-between align-items-center mb-3">
    <h4 class="mb-0 text-dark">Active Plans</h4>
</div>
<hr class="border-dark">
<div class="row g-4">

    <!-- Plan Card -->
    {% for order in order_plan %}
    <div class="col-md-4">
        <div class="card shadow-sm h-100">
            <div class="card-body">
                <h5 class="card-title">{{order.plan.name}}</h5>
                <!-- <p class="text-muted mb-2">Plan ID: PLAN-001</p> -->
                <p><strong>Percent:</strong>
                    {{order.plan.percent_increment|floatformat:1}}%
                </p>
                <p><strong>Started:</strong> {{order.created_at}}</p>
                <p><strong>Allocated:</strong> ${{order.principal_amount|floatformat:2|intcomma}}</p>
                <p><strong>Current Value:</strong> ${{order.current_value|floatformat:2|intcomma}}</p>
            </div>
            <div class="card-footer bg-white border-0">
                <div class="d-flex justify-content-between">
                    <a href="{% url 'staff:snapshot_positive' order.id %}" class="btn btn-success btn-sm">
                        <i class="bi bi-play-fill"></i> Spin Up
                    </a>
                    <a href="{% url 'staff:snapshot_negative' order.id %}" class="btn btn-warning btn-sm">
                        <i class="bi bi-pause-fill"></i> Spin Down
                    </a>
                    <!-- <a href="{% url 'staff:snapshot_positive' order.id %}" class="btn btn-primary btn-sm">
                        <i class="bi bi-pencil-square"></i> Edit
                    </a> -->
                </div>
            </div>
        </div>
    </div>
    {% empty%}
        <p class="text-muted">No Available Active plan for this customer</p>
    {% endfor %}
</div>

{% endblock %}

templates/staff/dashboard.html
{% extends "../customer/base.html" %}

{% block title %}Admin Dashboard{% endblock %}

{% block content %}
<div class="container mt-5">
    {% include "../notification/messages.html" %}
    <div class="row">
        <div class="col-5 col-sm-8">
            <h4 class="text-dark">Customer List</h4>
        </div>
    </div>

    <hr class="mt-0 border-dark">
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover mt-3">
            <thead class="table-dark">
                <tr>
                    <th>Full Name</th>
                    <th>Email</th>
                    <th>Nickname</th>
                    <th>Date Joined</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for customer in customers %}
                <tr>
                    <td>{{ customer.full_name }}</td>
                    <td>{{ customer.email }}</td>
                    <td>{{ customer.nick_name|default:"-" }}</td>
                    <td>{{ customer.date_joined|date:"Y-m-d" }}</td>
                    {% if customer.is_active%}
                    <td>Active</td>
                    {% else %}
                    <td>Inactive</td>
                    {% endif %}
                    <td>
                        <a href="{% url 'staff:admin_customer_detail' customer.id %}"
                            class="me-3 btn btn-primary btn-sm">
                            View Details
                        </a>
                        <a href="{% url 'staff:admin_edit_customer' customer.id %}"
                            class="btn btn-info text-white btn-sm">
                            Edit
                        </a>
                        <a href="{% url 'staff:admin_delete_customer' customer.id %}"
                            class="btn btn-danger btn-sm ms-2">
                            Delete
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5">No customers found.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/staff/delete_customer.html
{% extends "../customer/base.html" %}

{% block title %}Delete Customer{% endblock %}

{% block content %}
<div class="container my-4">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-6">

            <div class="card border-danger">
                <div class="card-body">
                    <h4 class="text-center text-danger">Delete Customer</h4>
                    <hr>

                    {% include "../notification/messages.html" %}

                    <p class="text-center mb-4">
                        Are you sure you want to delete
                        <strong>{{ customer.full_name }}</strong>?
                        <br>
                        <span class="text-danger small">
                            This action cannot be undone.
                        </span>
                    </p>

                    <form method="post" class="pinner-form" novalidate>
                        {% csrf_token %}

                        <button
                            type="submit"
                            class="btn btn-danger w-100 btn-sm fw-bold mb-2"
                            data-spinner-text="Deleting..."
                            data-spinner-class="btn-danger w-100"
                        >
                            Delete Customer
                        </button>

                        <a
                            href="{% url 'staff:admin_edit_customer' customer.id %}"
                            class="btn btn-secondary w-100 btn-sm fw-bold"
                        >
                            Cancel
                        </a>
                    </form>

                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

templates/staff/kyc_list.html
{% extends "../customer/base.html" %}

{% block title %}KYC List{% endblock %}

{% block content %}
{% include "../notification/messages.html" %}
<div class="row">
    <div class="col-5 col-sm-8">
        <h4>Kyc Submissions List</h4>
    </div>
</div>
<hr>
<div class="card">
    <div class="card-header">
        KYC Submissions
    </div>

    <div class="table-responsive">
        <table class="table align-middle mb-0">
            <thead class="table-light">
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th>Submitted</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>

                {% for kyc in kycs %}
                <tr>
                    <td>
                        {{ kyc.first_name }} {{ kyc.last_name }}
                    </td>

                    <td>
                        {{ kyc.portfolio.user.email }}
                    </td>

                    <td>
                        {% if kyc.status == "PENDING" %}
                        <span class="badge bg-warning">Pending</span>
                        {% elif kyc.status == "VERIFIED" %}
                        <span class="badge bg-success">Verified</span>
                        {% elif kyc.status == "REJECTED" %}
                        <span class="badge bg-danger">Rejected</span>
                        {% else %}
                        <span class="badge bg-secondary">Not Submitted</span>
                        {% endif %}
                    </td>

                    <td>
                        {{ kyc.submitted_at|date:"Y-m-d" }}
                    </td>

                    <td>
                        <a href="{% url 'staff:admin_kyc_review' kyc.pk %}" class="btn btn-sm btn-primary">
                            Review
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5" class="text-center text-muted py-4">
                        No KYC requests found.
                    </td>
                </tr>
                {% endfor %}

            </tbody>

        </table>
    </div>
</div>
{% endblock %}

templates/staff/kyc_review.html
{% extends "../customer/base.html" %}

{% block title %}KYC Review{% endblock %}

{% block content %}
<h4 class="mt-5 text-dark">
    KYC Review — {{ kyc.portfolio.user.email }}
</h4>
<hr class="border-dark mt-0 mb-3">
<div class="card mb-4">
    <div class="card-body d-flex justify-content-between align-items-center">

        <div>
            <small class="text-muted">Verification Status</small>
            <h5 class="mb-0">
                {{ kyc.get_status_display }}
            </h5>

            {% if kyc.submitted_at %}
            <small class="text-muted">
                Submitted: {{ kyc.submitted_at }}
            </small>
            {% endif %}
        </div>

        <span class="badge
            {% if kyc.status == 'VERIFIED' %}bg-success
            {% elif kyc.status == 'PENDING' %}bg-warning
            {% elif kyc.status == 'REJECTED' %}bg-danger
            {% else %}bg-secondary{% endif %}
        ">
            {{ kyc.get_status_display }}
        </span>

    </div>
</div>

{% if kyc.status == 'REJECTED' %}
<div class="alert alert-danger">
    <strong>Rejection Reason</strong><br>
    {{ kyc.rejection_reason }}
</div>
{% endif %}

<div class="card mb-4">
    <div class="card-header">Personal Information</div>
    <div class="card-body">

        <p><strong>Name:</strong> {{ kyc.first_name }} {{ kyc.last_name }}</p>
        <p><strong>Date of Birth:</strong> {{ kyc.date_of_birth }}</p>
        <p><strong>Nationality:</strong> {{ kyc.nationality }}</p>

    </div>
</div>

<div class="card mb-4">
    <div class="card-header">Identity Document</div>

    <div class="card-body">

        <p><strong>Type:</strong> {{ kyc.get_document_type_display }}</p>
        <p><strong>Number:</strong> {{ kyc.document_number }}</p>

        {% if kyc.document_image %}
        <img src="{{ kyc.document_image.url }}" class="img-fluid border rounded" style="max-width:400px;">
        {% endif %}

    </div>
</div>

<div class="card mb-4">
    <div class="card-header">Proof of Address</div>

    <div class="card-body">

        <p><strong>Address:</strong> {{ kyc.address }}</p>
        <p><strong>City:</strong> {{ kyc.city }}</p>
        <p><strong>Country:</strong> {{ kyc.country }}</p>

        {% if kyc.address_proof %}
        <img src="{{ kyc.address_proof.url }}" class="img-fluid border rounded" style="max-width:400px;">
        {% endif %}

    </div>
</div>


<div class="card">
    <div class="card-header">Review Action</div>

    <div class="card-body">

        <form method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label class="form-label">Rejection Reason (required if rejecting)</label>
                <textarea name="rejection_reason" class="form-control" rows="3"></textarea>
            </div>

            <div class="d-flex gap-2">
                <button type="submit" name="action" value="approve" class="btn btn-success">
                    Approve
                </button>

                <button type="submit" name="action" value="reject" class="btn btn-danger">
                    Reject
                </button>
            </div>
        </form>

    </div>
</div>
{% endblock %}

templates/staff/plan_confirm_delete.html
{% extends "../customer/base.html" %}

{% block title %}Delete plan{% endblock %}

{% block content %}
<div class="container my-4">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-6">
            <div class="card shadow-sm border-danger">
                <div class="card-body">
                    <h5 class="card-title text-danger">
                        Delete Plan
                    </h5>

                    <p class="mb-3">
                        Are you sure you want to delete
                        <strong>{{ plan.name }}</strong>?
                    </p>

                    <p class="text-muted">
                        This will permanently remove the plan and all its asset
                        allocations.
                    </p>

                    <form method="post" class="text-end pinner-form">
                        {% csrf_token %}
                        <a href="{% url 'staff:admin_plan_list' %}" class="btn btn-outline-secondary">
                            Cancel
                        </a>
                        <button type="submit" class="btn btn-danger btn-sm"
                        data-spinner-text="Deleting Plan..."
                        data-spinner-class="btn-secondary w-100">
                            Delete
                        </button>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

templates/staff/plan_list.html
{% extends "../customer/base.html" %}

{% block title %}Plans List{% endblock %}

{% block content %}
<div class="container mt-5">
    {% include "../notification/messages.html" %}
    <div class="row">
        <div class="col-5 col-sm-8">
            <h4 class="text-dark">Plans List</h4>
        </div>
        <div class="col-7 col-sm-4">
            <a href="{% url 'staff:admin_plan_create' %}" class="btn btn-primary btn-sm">Create New Plans</a>
        </div>
    </div>

    <hr class="mt-0 border-dark">
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover mt-3">
            <thead class="table-dark">
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Percent Increment</th>
                    <th>Minimum Amount</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for plan in plans %}
                <tr>
                    <td>{{ plan.name }}</td>
                    <td>
                        <span class="badge bg-secondary">
                            {{ plan.plantype }}
                        </span>
                    </td>
                    <td>
                        {{ plan.percent_increment|floatformat:2 }}%
                    </td>
                    <td>
                        ${{ plan.min_amount|floatformat:2}}
                    </td>
                    <td>
                        <div class="d-flex">
                            <a href="{% url 'staff:admin_plan_edit' plan.id %}"
                                class="btn btn-sm btn-outline-primary me-1">
                                <i class="bi bi-pencil-square"></i> Edit
                            </a>

                            <a href="{% url 'staff:admin_plan_delete' plan.id %}"
                                class="btn btn-sm btn-outline-danger">
                                <i class="bi bi-trash"></i> Delete
                            </a>
                        </div>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5">No plans found.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>
{% endblock %}