account/urls.py
from django.urls import path, include

from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('account-created/', views.account_created_view, name='account_created'),
    path("verify-email/<uidb64>/<token>/", views.verify_email,
        name="verify_email",),
    path('resend-verification/', views.resend_verification_view, name='resend_verification'),
    path('login/', views.EmailLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('account/', include('account.urls', namespace='account')),
    path('otp/', include('otp.urls', namespace='otp')),
    path('user/', include('customer.urls', namespace='customer')),
    path('staff/', include('staff.urls', namespace='staff')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('about-us/', views.about_view, name='about'),
    path('contact-us/', views.contact_view, name='contact'),
]

otp/urls.py
from django.urls import path
from . import views

app_name = 'otp'

urlpatterns = [
    path('login-verify/', views.login_verify_otp_view, name='login_verify_otp'),
    path('resend-otp/', views.resend_otp_view, name='resend_otp'),
]

frontend/views.py
from django.shortcuts import render

def home_view(request):
    return render(request, 'frontend/index.html')

def about_view(request):
    return render(request, 'frontend/about.html')

def contact_view(request):
    return render(request, 'frontend/contact.html')

templates/frontend/includes/footer.html
{% load static %}
<!-- main-footer -->
<footer class="main-footer bg-color-2">
    <div class="footer-top">
        <div class="auto-container">
            <div class="footer-top-content">
                <div class="form-inner">
                    <form method="post" action="#">
                        <div class="form-group">
                            <input type="email" name="email" placeholder="Your email address...">
                            <button type="submit" class="theme-btn"><span>subscribe</span></button>
                        </div>
                    </form>
                    <h2>Become a part</h2>
                </div>
                <div class="lower-box">
                    <h2>of our update community...</h2>
                    <div class="subscriber-box">
                        <figure class="thumb-box"><img src="{% static 'frontend/assets/images/resource/thumb-1.jpg' %}" alt=""></figure>
                        <span>5M+</span>
                        <h6>Subscribers</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="widget-section">
        <div class="auto-container">
            <div class="row clearfix">
                <div class="col-lg-3 col-md-6 col-sm-12 footer-column">
                    <div class="footer-widget logo-widget">
                        <figure class="footer-logo"><a href="{% url 'frontend:home' %}"><img src="{% static 'account/images/logo-stone.png' %}" alt="footer-logo" width="200"></a>
                        </figure>
                        <p>Access valuable insights and expertise download free trading guides today!..</p>
                        <div class="link-box">
                            <div class="icon-box"><i class="flaticon-book"></i></div>
                            <h6><a href="{% url 'frontend:home' %}">Free <br>Trading Guides <i class="flaticon-right-arrow"></i></a>
                            </h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-12 footer-column">
                    <div class="footer-widget links-widget">
                        <div class="widget-title">
                            <h3>Contact</h3>
                        </div>
                        <div class="widget-content">
                            <ul class="links-list clearfix">
                                <li><a href="index.html">Email Us</a></li>
                                <li><a href="index.html">Help Center</a></li>
                                <li><a href="faq.html">Faq's</a></li>
                                <li><a href="index.html">Live Chat</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-12 footer-column">
                    <div class="footer-widget links-widget">
                        <div class="widget-title">
                            <h3>Useful Links</h3>
                        </div>
                        <div class="widget-content">
                            <div class="row clearfix">
                                <div class="col-lg-6 col-md-6 col-sm-12 links-column">
                                    <ul class="links-list clearfix">
                                        <li><a href="{% url 'frontend:home' %}">Home</a></li>
                                        <li><a href="index.html">Story</a></li>
                                        <li><a href="index.html">History</a></li>
                                        <li><a href="team.html">Our Team</a></li>
                                        <li><a href="index.html">Trading Rules</a></li>
                                        <li><a href="blog.html">Blog Post</a></li>
                                    </ul>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12 links-column">
                                    <ul class="links-list clearfix">
                                        <li><a href="index.html">Markets</a></li>
                                        <li><a href="index.html">Evaluations</a></li>
                                        <li><a href="index.html">Affiliates</a></li>
                                        <li><a href="index.html">Pricing</a></li>
                                        <li><a href="index.html">Get Funded</a></li>
                                        <li><a href="index.html">Course</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12 footer-column">
                    <div class="footer-widget contact-widget">
                        <div class="widget-title">
                            <h3>Social Connect</h3>
                        </div>
                        <div class="widget-content">
                            <!-- <ul class="social-links">
                                <li><a href="index.html"><i class="flaticon-facebook"></i></a></li>
                                <li><a href="index.html"><i class="flaticon-user"></i></a></li>
                                <li><a href="index.html"><i class="flaticon-instagram-logo"></i></a></li>
                                <li><a href="index.html"><i class="flaticon-youtube"></i></a></li>
                            </ul> -->
                            <ul class="download-list">
                                <li class="app-store">
                                    <a href="#"><i class="flaticon-apple"></i>App Store</a>
                                </li>
                                <li class="play-store">
                                    <a href="#"><img src="{% static 'frontend/assets/images/icons/icon-18.png' %}" alt="">Google
                                        Play</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="auto-container">
            <div class="bottom-inner">
                <div class="copyright">
                    <p>&copy; 2026 <a href="{% url 'frontend:home' %}">StoneCrest Capital</a> Made with Expertise, All Rights Reserved.</p>
                </div>
                <ul class="footer-nav">
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Terms & Conditions</a></li>
                    <li><a href="#">Legal</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!-- main-footer end -->

templates/frontend/includes/navbar.html
{% load static %}
<!-- main header -->
<header class="main-header">
    <!-- header-top -->
    <div class="header-top">
        <div class="outer-container">
            <div class="top-inner">
                <div class="left-column">
                    <div class="login-box">
                        <div class="icon-box"><img src="{% static 'frontend/assets/images/icons/icon-1.png' %}" alt=""></div>
                        <h5><a href="{% url 'account:login' %}">Login </a><span>-or</span></h5>
                        <h6><a href="{% url 'account:register' %}">Create your account</a></h6>
                    </div>
                    <div class="language-box">
                        <div class="icon-box"><i class="flaticon-earth"></i></div>
                        <div class="select-box">
                            <select class="wide">
                                <option data-display="En">En</option>
                                <option value="1">Ch</option>
                                <option value="2">Hi</option>
                                <option value="3">Sp</option>
                                <option value="4">Tu</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="text-box">
                    <div class="icon-box"><img src="{% static 'frontend/assets/images/icons/icon-2.png' %}" alt=""></div>
                    <h6>Traders payouts since 2025: <span>$36,769,485</span></h6>
                </div>
                <div class="right-column">
                    <div class="search-box">
                        <form method="post" action="#">
                            <div class="form-group">
                                <input type="search" name="search-field" placeholder="Search" required="">
                                <button type="submit"><i class="flaticon-search"></i></button>
                            </div>
                        </form>
                    </div>
                    <div class="mail-box">
                        <div class="icon-box"><img src="{% static 'frontend/assets/images/icons/icon-3.png' %}" alt=""></div>
                        <h5>Mail us</h5>
                        <h6><a href="mailto:support@stonecrestcapital.com">support@stonecrestcapital.com</a></h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- header-lower -->
    <div class="header-lower">
        <div class="outer-container">
            <div class="outer-box">
                <div class="logo-box">
                    <figure class="logo"><a href="{% url 'frontend:home' %}"><img src="{% static 'account/images/logo-stone-black.png' %}" alt="" width="200"></a></figure>
                </div>
                <div class="menu-area clearfix">
                    <!--Mobile Navigation Toggler-->
                    <div class="mobile-nav-toggler">
                        <i class="icon-bar"></i>
                        <i class="icon-bar"></i>
                        <i class="icon-bar"></i>
                    </div>
                    <nav class="main-menu navbar-expand-md navbar-light">
                        <div class="collapse navbar-collapse show clearfix" id="navbarSupportedContent">
                            <ul class="navigation clearfix">
                                <li class="current"><a href="{% url 'frontend:home' %}">Home</a>
                                </li>
                                <li class=""><a href="{% url 'frontend:about' %}">About</a>
                                </li>
                                <li class=""><a href="{% url 'frontend:home' %}">Services</a>
                                </li>
                                <li><a href="{% url 'frontend:contact' %}">Contact</a></li>
                                <li><a href="{% url 'account:register' %}">Register</a></li>
                                <li><a href="{% url 'account:login' %}">Login</a></li>
                            </ul>
                        </div>
                    </nav>
                </div>
                <div class="menu-right-content">
                    <div class="link-box">
                        <div class="icon-box"><i class="flaticon-bandwidth"></i></div>
                        <h6><a href="{% url 'account:register' %}">Get<br>Started <i class="flaticon-right-arrow"></i></a></h6>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--sticky Header-->
    <div class="sticky-header">
        <div class="outer-container">
            <div class="outer-box">
                <div class="logo-box">
                    <figure class="logo"><a href="{% url 'account:register' %}"><img src="{% static 'account/images/logo-stone-black.png' %}" alt="logo" width="180"></a></figure>
                </div>
                <div class="menu-area clearfix">
                    <nav class="main-menu clearfix">
                        <!--Keep This Empty / Menu will come through Javascript-->
                    </nav>
                </div>
                <div class="menu-right-content">
                    <div class="link-box">
                        <div class="icon-box"><i class="flaticon-bandwidth"></i></div>
                        <h6><a href="{% url 'frontend:home' %}">Get <br>Started <i class="flaticon-right-arrow"></i></a></h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- main-header end -->


<!-- Mobile Menu  -->
<div class="mobile-menu">
    <div class="menu-backdrop"></div>
    <div class="close-btn"><i class="fas fa-times"></i></div>

    <nav class="menu-box">
        <div class="nav-logo"><a href="{% url 'frontend:home' %}"><img src="{% static 'account/images/logo-stone.png' %}" alt="" title="" width="170"></a></div>
        <div class="menu-outer"><!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header--></div>
        <div class="contact-info">
            <h4>Contact Info</h4>
            <ul>
                <li>Chicago 12, Melborne City, USA</li>
                <li><a href="tel:+8801682648101">+88 01682648101</a></li>
                <li><a href="mailto:support@stonecrestcapital.com">support@stonecrestcapital.com</a></li>
            </ul>
        </div>
    </nav>
</div><!-- End Mobile Menu -->