base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('account/', include('account.urls', namespace='account')),
    path('otp/', include('otp.urls', namespace='otp')),
    path('user/', include('customer.urls', namespace='customer')),
    path('staff/', include('staff.urls', namespace='staff')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

customer/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('dashboard/', views.customer_dashboard_view, name='customer_dashboard'),
    path('copy-experts/', views.copy_experts, name='copy_experts'),
    path('settings-and-security/', views.settings_security, name='settings_security'),

    path('verify-kyc/', views.verify_kyc_view, name='verify_kyc'),
    path('reits/', views.reits_view, name='reits'),
    path('all-plans/', views.all_plans_view, name='all_plans'),

    # transaction
    path('user/deposit/', views.customer_deposit_view, name='customer_deposit'),
    path('user/withdraw/', views.customer_withdraw_view, name='customer_withdraw'),

    # plan
    path('active-plans/', views.active_plan_list_view, name='active_plan_list'),
    path('activate-plan/<plan_id>/', views.activate_plan_view, name='activate_plan'),

    # order
    path('orderplan-detail/<order_id>/', views.orderplan_detail_view, name='orderplan_detail'),

    # auth
    path('change_password/', views.change_password, name='change_password'),
    path('submit-vip-request/', views.submit_vip_request, name='submit_vip_request'),
    
]

otp/urls.py
from django.urls import path
from . import views

app_name = 'otp'

urlpatterns = [
    path('login-verify/', views.login_verify_otp_view, name='login_verify_otp'),
    path('resend-otp/', views.resend_otp_view, name='resend_otp'),
]

staff/urls.py
from django.urls import path

from . import views

app_name = 'staff'

urlpatterns = [
    path('dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('customer/<int:user_id>/detail/',views.admin_customer_detail_view,
    name='admin_customer_detail'),
    path("customer/<int:user_id>/edit/", views.admin_edit_customer_view,
    name="admin_edit_customer"),
    path("customers/<int:user_id>/delete/", views.admin_delete_customer_view,
    name="admin_delete_customer"),

    path('plans/', views.admin_plan_list_view,name='admin_plan_list'),
    path('plan/create/', views.admin_plan_create_view,name='admin_plan_create'),
    path('plan/<int:pk>/edit/', views.admin_plan_edit_view,
    name='admin_plan_edit'),
    path('plan/<int:pk>/delete/', views.admin_plan_delete_view,
    name='admin_plan_delete'),

    path('pending-deposits/', views.admin_deposit_requests_view, name='admin_deposit_requests'),
    path('pending-withdrawals/', views.admin_withdraw_requests_view, name='admin_withdraw_requests'),

    path('kyc-list/', views.admin_kyc_list_view,name='admin_kyc_list'),
    path('kyc/<int:kyc_id>/review/', views.admin_kyc_review_view,
    name='admin_kyc_review'),

    path('snapshot-positive/<int:order_id>/', views.snapshot_positive_view,
    name='snapshot_positive'),
    path('snapshot-negative/<int:order_id>/', views.snapshot_negative_view,
    name='snapshot_negative'),

    path('vip-requests/', views.vip_requests_admin,
    name='vip_requests'),
    path('vip_request_action/<int:request_id>/<str:action>/', views.vip_request_action,
    name='vip_request_action'),
]

customer/models.py
from django.db import models
from django.contrib.auth import get_user_model
from decimal import Decimal

User = get_user_model()

class Portfolio(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cash_balance = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        default=Decimal('0.00')
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} Portfolio"
    
    @property
    def is_kyc_verified(self):
        return hasattr(self, "kyc") and self.kyc.status == "VERIFIED"

customer/forms.py
from django import forms
from django_countries.widgets import CountrySelectWidget
from django_countries import countries
from django.utils import timezone

from account.models import KYC


class KYCForm(forms.ModelForm):
    class Meta:
        model = KYC
        fields = [
            # Personal info
            'first_name',
            'last_name',
            'date_of_birth',
            'nationality',

            # Identity document
            'document_type',
            'document_number',
            'document_image',

            # Address
            'address',
            'city',
            'country',
            'address_proof',
        ]

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(
                attrs={'class': 'form-control', 'type': 'date'}
            ),
            'nationality': forms.TextInput(attrs={'class': 'form-control'}),

            'document_type': forms.Select(attrs={'class': 'form-select'}),
            'document_number': forms.TextInput(attrs={'class': 'form-control'}),
            'document_image': forms.ClearableFileInput(attrs={'class': 'form-control'}),

            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'country': forms.TextInput(attrs={'class': 'form-control'}),
            'address_proof': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

    def clean(self):
        cleaned_data = super().clean()

        # Required document fields
        if not cleaned_data.get('document_type'):
            self.add_error('document_type', 'Please select a document type.')

        if not cleaned_data.get('document_number'):
            self.add_error('document_number', 'Document number is required.')

        if not cleaned_data.get('document_image'):
            self.add_error('document_image', 'Please upload your identity document.')

        if not cleaned_data.get('address_proof'):
            self.add_error('address_proof', 'Please upload proof of address.')

        return cleaned_data

    def save(self, commit=True):
        kyc = super().save(commit=False)

        # Mark as submitted
        kyc.status = KYC.STATUS_PENDING
        kyc.submitted_at = timezone.now()

        if commit:
            kyc.save()

        return kyc

customer/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import transaction
from django.db.models import Sum
from decimal import Decimal
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth import update_session_auth_hash

from .models import Portfolio
from .forms import KYCForm
from account.models import KYC, VIPRequest
from account.forms import BootstrapPasswordChangeForm, VIPRequestForm
from plan.models import Plan, OrderPlan
from transaction.forms import CustomerTransactionForm

@login_required
def customer_dashboard_view(request):
    portfolio = Portfolio.objects.get(user=request.user)
    plans = Plan.objects.filter(is_featured=True)

    context = {
        "current_url": request.resolver_match.url_name,
        "portfolio": portfolio,
        "plans": plans
    }
    return render(request, "customer/dashboard.html", context)


@login_required
def copy_experts(request):
    user = request.user
    has_pending_vip_request = VIPRequest.objects.filter(user=user, status='pending').exists()
    context = {
        "current_url": request.resolver_match.url_name,
        "user": user,
        "has_pending_vip_request": has_pending_vip_request
    }
    return render(request, "customer/copy_experts.html", context)


@login_required
def settings_security(request):
    portfolio = get_object_or_404(Portfolio, user=request.user)
    password_form = BootstrapPasswordChangeForm(portfolio.user)

    context = {
        "current_url": request.resolver_match.url_name,
        'portfolio': portfolio,
        "password_form":password_form,
    }
    return render(request, "customer/settings_security.html", context)


@login_required
def verify_kyc_view(request):
    portfolio = get_object_or_404(Portfolio, user=request.user)

    # Get or create KYC record
    kyc, created = KYC.objects.get_or_create(portfolio=portfolio)

    # If already verified, block resubmission
    if kyc.is_verified:
        messages.info(request, "Your identity has already been verified.")
        return redirect('customer:customer_dashboard')

    if request.method == "POST":
        form = KYCForm(request.POST, request.FILES, instance=kyc)

        if form.is_valid():
            form.save()
            messages.success(
                request,
                "Your KYC documents have been submitted successfully and are pending verification."
            )
            return redirect('customer:verify_kyc')
    else:
        form = KYCForm(instance=kyc)

    return render(
        request,
        'customer/verify_kyc.html',
        {
            'form': form,
            'kyc': kyc,
            'portfolio': portfolio,
            'current_url': request.resolver_match.url_name,
        }
    )



# transaction part
@login_required
@transaction.atomic
def customer_deposit_view(request):
    portfolio = request.user.portfolio
    deposit_transactions = portfolio.transactions.filter(
        transaction_type='DEPOSIT'
    )

    if request.method == "POST":
        form = CustomerTransactionForm(request.POST, transaction_type="DEPOSIT")

        if form.is_valid():
            trans = form.save(commit=False)
            trans.transaction_type = 'DEPOSIT'
            trans.portfolio = portfolio

            trans.balance = portfolio.cash_balance
            trans.save()

            messages.success(request, "Your deposit request has been received and is currently being processed.")
            return redirect('customer:customer_deposit')
        else:
            # 🔥 THIS shows you exactly why the form is invalid
            messages.error(request, "An error occurred while processing your request. Please try again or contact support if the issue persists.")
            print("FORM ERRORS:", form.errors)
            print("NON FIELD ERRORS:", form.non_field_errors())
    else:
        form = CustomerTransactionForm()

    return render(
        request,
        "customer/transactions/customer_deposit.html",
        {
            "form": form,
            "transactions": deposit_transactions
        }
    )


@login_required
@transaction.atomic
def customer_withdraw_view(request):
    portfolio = request.user.portfolio

    # Only fetch withdraw transactions once
    withdraw_transactions = portfolio.transactions.filter(
        transaction_type='WITHDRAW'
    )

    # Pending withdraws and total in a single query
    pending_withdraw_sum = withdraw_transactions.filter(
        status='PENDING'
    ).aggregate(
        total=Sum('amount')
    )['total'] or 0

    if request.method == "POST":
        form = CustomerTransactionForm(request.POST, transaction_type="WITHDRAW")

        if form.is_valid():
            trans = form.save(commit=False)
            trans.transaction_type = 'WITHDRAW'
            trans.portfolio = portfolio

            # Check if balance is sufficient
            if portfolio.cash_balance < trans.amount:
                messages.error(
                    request,
                    "You don't have enough cash balance to complete this withdrawal."
                )
            else:

                if not portfolio.is_kyc_verified:
                    messages.error(
                        request,
                        "You must complete identity verification (KYC) before making a withdrawal."
                    )
                    return redirect('customer:verify_kyc')
                # Deduct from balance and save
                portfolio.cash_balance -= trans.amount
                portfolio.save()

                trans.balance = portfolio.cash_balance
                trans.save()
                messages.success(
                    request,
                    "Your withdrawal request has been submitted successfully and is pending processing."
                )
                return redirect('customer:customer_withdraw')

    else:
        form = CustomerTransactionForm()

    return render(
        request,
        "customer/transactions/customer_withdraw.html",
        {
            "form": form,
            "transactions": withdraw_transactions,
            "portfolio": portfolio,
            "pending_withdraw_sum": pending_withdraw_sum,
        }
    )


@login_required
def reits_view(request):
    portfolio = get_object_or_404(Portfolio, user=request.user)
    reit_plans = Plan.objects.filter(plantype="REIT")

    context = {
        "current_url": request.resolver_match.url_name,
        "portfolio": portfolio,
        "reit_plans": reit_plans,
    }
    return render(request, "customer/reits.html", context)


@login_required
def all_plans_view(request):
    portfolio = get_object_or_404(Portfolio, user=request.user)
    plans = Plan.objects.exclude(plantype=Plan.PlanType.REIT)

    context = {
        "current_url": request.resolver_match.url_name,
        "portfolio": portfolio,
        "plans": plans,
    }
    return render(request, "customer/all_plans.html", context)


@login_required
def activate_plan_view(request, plan_id):
    portfolio = request.user.portfolio
    plan = get_object_or_404(Plan, id=plan_id)

    if request.method == "POST":
        allocated_cash = Decimal(request.POST.get("allocated_cash", "0"))

        if allocated_cash < plan.min_amount: 
            messages.error(request, f"Minimum amount for this plan is ${plan.min_amount}.") 
            return redirect('customer:activate_plan', plan_id=plan.pk)
        
        if allocated_cash > portfolio.cash_balance:
            messages.error(
                request,
                "Allocated cash exceeds your available cash balance."
            )
            return redirect('customer:activate_plan', plan_id=plan.pk)
        
        # 1️⃣ Deduct allocated cash from follower only once
        portfolio.cash_balance -= allocated_cash
        portfolio.save(update_fields=['cash_balance'])

        order = OrderPlan.objects.create( 
            portfolio=portfolio, 
            plan=plan, 
            principal_amount=allocated_cash, 
            current_value=allocated_cash, 
            start_at=timezone.now(), 
            status=OrderPlan.STATUS_ACTIVE, 
        )

        messages.success(request, f"'{plan.name}' activated with ${allocated_cash}.") 
        return redirect('customer:customer_dashboard')

    return render(
        request,
        "customer/activate_plan.html",
        {
            "plan": plan,
            "portfolio": portfolio
        }
    )


@login_required
def active_plan_list_view(request):
    portfolio = request.user.portfolio
    active_plans = OrderPlan.objects.filter(portfolio=portfolio)

    return render(
        request,
        "customer/active_plan_list.html",
        {
            "active_plans": active_plans,
            "portfolio": portfolio
        }
    )


@login_required
def orderplan_detail_view(request, order_id):
    portfolio = request.user.portfolio
    order = get_object_or_404(OrderPlan, pk=order_id, portfolio=portfolio) 
    
    snapshots_qs = order.items.order_by('snapshot_at')

    # -------- Pagination --------
    paginator = Paginator(snapshots_qs, 15)  # Show 10 snapshots per page
    page_number = request.GET.get('page')
    snapshots = paginator.get_page(page_number)

    # -------- Chart Data (Optional: Use ALL snapshots or only current page) --------
    # If you want chart to show ALL data:
    all_snapshots = snapshots_qs

    labels = [item.snapshot_at.strftime("%Y-%m-%d") for item in all_snapshots]
    values = [float(item.cumulative_amount or order.principal_amount) for item in all_snapshots]

    context = { 
        'order': order, 
        'snapshots': snapshots,   # paginated snapshots
        'labels': labels,
        'values': values,
    }

    return render(
        request,
        "customer/order_plan_detail.html",
        context
    )


@login_required
def change_password(request):

templates/customer/includes/navbar.html
{% load static %}
<!-- Mobile Navbar -->
<nav class="navbar navbar-dark bg-dark d-lg-none px-3">
  <button class="btn btn-outline-light" data-bs-toggle="offcanvas" data-bs-target="#mobileSidebar">☰</button>
  <span class="navbar-brand ms-2">Command Center</span>
</nav>

<!-- Mobile Sidebar -->
<div class="offcanvas offcanvas-end bg-dark text-white" tabindex="-1" id="mobileSidebar">
  <div class="offcanvas-header">
    <div class="logo">
      <img src="{% static 'account/images/logo-stone.png' %}" alt="" width="130">
    </div>
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"></button>
  </div>
  <!-- <hr class="border-white"> -->
  <div class="offcanvas-body mt-5">
    <ul class="nav flex-column">
      {% if not request.user.is_staff %}
      <li>
        <a class="nav-link {% if current_url == 'customer_dashboard' %}active{% endif %}"
          href="{% url 'customer:customer_dashboard' %}">
          <i class="bi bi-speedometer2 me-2"></i>
          Command Center
        </a>
      </li>
      <!-- <li><a class="nav-link" href="#"><i class="bi bi-briefcase me-2"></i> Capital Allocation</a></li> -->
      <li>
        <a class="nav-link {% if current_url == 'reits' %}active{% endif %}" href="{% url 'customer:reits' %}">
          <i class="bi bi-buildings me-2"></i>
          Real Estate Trusts
        </a>
      </li>
      <li><a class="nav-link" href="#"><i class="bi bi-diagram-3 me-2"></i> Asset Management</a></li>
      <li>
        <a class="nav-link {% if current_url == 'copy_experts' %}active{% endif %}"
          href="{% url 'customer:copy_experts' %}">
          <i class="bi bi-people me-2"></i>
          Strategic Mirroring
        </a>
      </li>
      <li>
        <a class="nav-link {% if current_url == 'settings_security' %}active{% endif %}"
          href="{% url 'customer:settings_security' %}">
          <i class="bi bi-people me-2"></i>
          Settings & Security
        </a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link {% if current_url == 'admin_dashboard' %}active{% endif %}"
          href="{% url 'staff:admin_dashboard' %}">
          <i class="bi bi-speedometer2 me-2"></i>
          Dashboard
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if current_url == 'admin_plan_list' %}active{% endif %}"
          href="{% url 'staff:admin_plan_list' %}">
          <i class="bi bi-diagram-3 me-2"></i>
          All Plans
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if current_url == 'admin_deposit_requests' %}active{% endif %}"
          href="{% url 'staff:admin_deposit_requests' %}">
          <i class="bi bi-cash-stack me-2"></i>
          Deposit Requests
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if current_url == 'admin_withdraw_requests' %}active{% endif %}"
          href="{% url 'staff:admin_withdraw_requests' %}">
          <i class="bi bi-arrow-down-circle me-2"></i>
          Withdrawal Requests
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if current_url == 'admin_kyc_list' %}active{% endif %}"
          href="{% url 'staff:admin_kyc_list' %}">
          <i class="bi bi-arrow-down-circle me-2"></i>
          KYC Submissions
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if current_url == 'vip_requests' %}active{% endif %}"
          href="{% url 'staff:vip_requests' %}">
          <i class="bi bi-arrow-down-circle me-2"></i>
          VIP Requests
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
</div>

<!-- Desktop Sidebar -->
<div class="sidebar d-none d-lg-block">
  <div class="logo">
    <img src="{% static 'account/images/logo-stone.png' %}" alt="" width="130">
  </div>
  <!-- <hr class="border-white"> -->

  <ul class="nav flex-column mt-5">
    {% if not request.user.is_staff %}
    <li>
      <a class="nav-link {% if current_url == 'customer_dashboard' %}active{% endif %}"
        href="{% url 'customer:customer_dashboard' %}">
        <i class="bi bi-speedometer2 me-2"></i>
        Command Center
      </a>
    </li>
    <!-- <li><a class="nav-link" href="#"><i class="bi bi-briefcase me-2"></i> Capital Allocation</a></li> -->
    <li>
      <a class="nav-link {% if current_url == 'reits' %}active{% endif %}" href="{% url 'customer:reits' %}">
        <i class="bi bi-buildings me-2"></i>
        Real Estate Trusts
      </a>
    </li>
    <li><a class="nav-link" href="#"><i class="bi bi-diagram-3 me-2"></i> Asset Management</a></li>
    <li>
      <a class="nav-link {% if current_url == 'copy_experts' %}active{% endif %}"
        href="{% url 'customer:copy_experts' %}">
        <i class="bi bi-people me-2"></i>
        Strategic Mirroring
      </a>
    </li>
    <li>
      <a class="nav-link {% if current_url == 'settings_security' %}active{% endif %}"
        href="{% url 'customer:settings_security' %}">
        <i class="bi bi-people me-2"></i>
        Settings & Security
      </a>
    </li>
    {% else %}
    <li class="nav-item">
      <a class="nav-link {% if current_url == 'admin_dashboard' %}active{% endif %}"
        href="{% url 'staff:admin_dashboard' %}">
        <i class="bi bi-speedometer2 me-2"></i>
        Dashboard
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if current_url == 'admin_plan_list' %}active{% endif %}"
        href="{% url 'staff:admin_plan_list' %}">
        <i class="bi bi-diagram-3 me-2"></i>
        All Plans
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if current_url == 'admin_deposit_requests' %}active{% endif %}"
        href="{% url 'staff:admin_deposit_requests' %}">
        <i class="bi bi-cash-stack me-2"></i>
        Deposit Requests
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if current_url == 'admin_withdraw_requests' %}active{% endif %}"
        href="{% url 'staff:admin_withdraw_requests' %}">
        <i class="bi bi-arrow-down-circle me-2"></i>
        Withdrawal Requests
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if current_url == 'admin_kyc_list' %}active{% endif %}"
        href="{% url 'staff:admin_kyc_list' %}">
        <i class="bi bi-arrow-down-circle me-2"></i>
        KYC Submissions
      </a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if current_url == 'vip_requests' %}active{% endif %}"
          href="{% url 'staff:vip_requests' %}">
          <i class="bi bi-arrow-down-circle me-2"></i>
          VIP Requests
        </a>
      </li>
    {% endif %}
  </ul>
</div>